name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Cache source data
        id: cache-data
        uses: actions/cache@v3
        with:
          path: |
            public/tree_species.parquet
            scripts/datasets/blr-tree-census/bbmp_tree_census_july2025.kml
          key: source-data-v1-${{ hashFiles('public/tree_species.parquet') }}

      - name: Install Python dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate GeoJSON files
        run: python scripts/tree_census_points_generator.py --tree-census-data scripts/datasets/blr-tree-census/bbmp_tree_census_july2025.kml --tree-bloom-data public/tree_species.parquet --output-dir public/geojson

      - name: Install Node dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4